Controllers/AvaliacaoController.cs
using Microsoft.AspNetCore.Mvc;

namespace CollabBridge.Controllers
{
    public class AvaliacaoController : Controller
    {
        public IActionResult IndexAval()
        {
            return View();
        }
    }
}

Controllers/DocumentoController.cs
using CollabBridge.Data;
using CollabBridge.Models;
using Microsoft.AspNetCore.Mvc;

namespace CollabBridge.Controllers
{
    public class DocumentoController : Controller
    {

        readonly private ApplicationDbContext _db;

        public DocumentoController(ApplicationDbContext db)
        {
                _db = db;
        }

        public IActionResult IndexDoc()
        {
            IEnumerable<DocumentosModel> documentos = _db.Documentos;
            return View(documentos);
        }
        [HttpGet]
        public IActionResult CadastrarDoc() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarDoc(DocumentosModel documentos)
        {
            if(ModelState.IsValid)
            {
                _db.Documentos.Add(documentos);
                _db.SaveChanges();

                return RedirectToAction("IndexDoc");
            }

            return View();
        }

        [HttpGet]
        public IActionResult EditarDoc(int? id)
        {
            if(id == null || id == 0) 
            {
                return NotFound();
            }

            DocumentosModel documento = _db.Documentos.FirstOrDefault(x => x.Id == id);

            if(documento == null) 
            {
                return NotFound();
            }
            return View(documento); 
        }

        [HttpPost]
        public IActionResult EditarDoc(DocumentosModel documento) 
        {
            if(ModelState.IsValid) 
            {
                _db.Documentos.Update(documento);
                _db.SaveChanges();

                return RedirectToAction("IndexDoc");
            }

            return View(documento);
        }
        [HttpGet]
        public IActionResult ExcluirDoc(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            DocumentosModel documento = _db.Documentos.FirstOrDefault(x => x.Id == id);

            if (documento == null)
            {
                return NotFound();
            }
            return View(documento);
        }
        [HttpPost]
        public IActionResult ExcluirDoc(DocumentosModel documento) 
        {
            if (documento == null) 
            {
                return NotFound();
            }
            
            _db.Documentos.Remove(documento);
            _db.SaveChanges();

            return RedirectToAction("IndexDoc");
        }


    }
}

Controllers/LoginController.cs
using CollabBridge.Data;
using CollabBridge.Models;
using Microsoft.AspNetCore.Mvc;

namespace CollabBridge.Controllers
{
    public class LoginController : Controller
    {
        readonly private ApplicationDbContext _db;

        public LoginController(ApplicationDbContext db)
        {
            _db = db;

        }
        public IActionResult IndexDeslogada()
        {
            return View();
        }

        public IActionResult QuemSomos()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Entrar(LoginModel loginModel)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    if (loginModel.Login == "adm" && loginModel.Senha == "123")
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    if (loginModel.Login == "padrao" && loginModel.Senha == "123")
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    TempData["MessagemErro"] = $"Usuário e/ou senha inválido(s). Por favor, tente novamente.";
                    }
                return View("IndexDeslogada");
            }
            catch (Exception erro)
            {
                TempData["MessagemErro"] = $"Algo deu errado: {erro.Message}";
                return RedirectToAction("IndexDeslogada");
            }
        }
    }
}

Controllers/UsuarioController.cs
using CollabBridge.Data;
using CollabBridge.Models;
using Microsoft.AspNetCore.Mvc;

namespace CollabBridge.Controllers
{
    public class UsuarioController : Controller
    {

        readonly private ApplicationDbContext _db;

        public UsuarioController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult IndexUser()
        {
            IEnumerable<UsuarioModel> usuarios = _db.Usuarios;
            return View(usuarios);
        }

        [HttpGet]
        public IActionResult CadastrarUser()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarUser(UsuarioModel usuarios)
        {
            if (ModelState.IsValid)
            {
                _db.Usuarios.Add(usuarios);
                _db.SaveChanges();

                return RedirectToAction("IndexUser");
            }

            return View();
        }

        [HttpGet]
        public IActionResult EditarUser(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            UsuarioModel usuarios = _db.Usuarios.FirstOrDefault(x => x.Id == id);

            if (usuarios == null)
            {
                return NotFound();
            }
            return View(usuarios);
        }

        [HttpPost]
        public IActionResult EditarUser(UsuarioModel usuarios)
        {
            if (ModelState.IsValid)
            {
                _db.Usuarios.Update(usuarios);
                _db.SaveChanges();

                return RedirectToAction("IndexUser");
            }

            return View(usuarios);
        }
        [HttpGet]
        public IActionResult ExcluirUser(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            UsuarioModel usuarios = _db.Usuarios.FirstOrDefault(x => x.Id == id);

            if (usuarios == null)
            {
                return NotFound();
            }
            return View(usuarios);
        }
        [HttpPost]
        public IActionResult ExcluirUser(UsuarioModel usuarios)
        {
            if (usuarios == null)
            {
                return NotFound();
            }

            _db.Usuarios.Remove(usuarios);
            _db.SaveChanges();


            return RedirectToAction("IndexUser");
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CollabBridge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CollabBridge.styles.css" asp-append-version="true" />

    <style>
        .custom-logout-button {
            background-color: red; 
            color: white; 
            padding: 5px 10px; 
            font-size: 14px; 
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">CollabBridge</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Avaliacao" asp-action="IndexAval">Avaliações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Documento" asp-action="IndexDoc">Documentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Treinamento" asp-action="IndexTrein">Treinamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Usuario" asp-action="IndexUser">Usuários</a>
                        </li>
                    </ul>
                    <a class="btn custom-logout-button" asp-controller="Login" asp-action="IndexDeslogada">Sair</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutDeslogada.cshtml
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CollabBridge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CollabBridge.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="">CollabBridge</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="IndexDeslogada">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="QuemSomos">Quem Somos Nós</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>